version: 0.2

env:
  secrets-manager:
    LOGIN: SonarCredentials:sonartoken
    HOST: SonarCredentials:host
    Organization: SonarCredentials:organization
    Project: SonarCredentials:projectKey

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - aws --version
      - aws aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i5c4z8t2
      - REPOSITORY_URI=public.ecr.aws/i5c4z8t2/ecr-ecart
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - echo build started on `date`
      - echo testi